name: dart_only
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  beat_generator: ^0.16.0
  lints: ^2.0.0
dependencies: {beat: ^0.14.1+2, build_runner: ^2.2.0}
