name: counter
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  beat:
  build_runner: ^2.2.0
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  beat_generator:
