targets:
  $default:
    builders:
      beat_station_data_generator:
        enabled: true
      beat_machine_generator:
        enabled: true

builders:
  beat_station_data_generator:
    import: "package:beat_generator/beat_generator.dart"
    builder_factories: ["beatStationDataGenerator"]
    build_extensions: { ".dart": [".beat_data.json"] }
    auto_apply: dependents
    runs_before: [":beat_machine_generator"]
    build_to: cache

  beat_machine_generator:
    import: "package:beat_generator/beat_generator.dart"
    builder_factories: ["beatMachineGenerator"]
    build_extensions: { ".dart": [".beat.dart"] }
    auto_apply: dependents
    build_to: source
