name: beat_generator
description: A starting point for Dart libraries or applications.
version: 0.1.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.2.0
  beat:
  build: ^2.3.0
  code_builder: ^4.1.0
  source_gen: ^1.2.2
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.11
  build_test: ^2.1.5
  lints: ^2.0.0
  test: ^1.16.0
