name: beat_generator
description: A code genrator for beat state management. Heavily inspired by xstate.js.org
version: 0.13.5+2
repository: https://github.com/beatly-dev/beat
issue_tracker: https://github.com/beatly-dev/beat/issues

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.2.0
  args: ^2.3.1
  beat: ">=0.0.0 <1.0.0"
  beat_config: ">=1.1.0"
  build: ^2.3.0
  build_config: ^1.1.0
  build_runner: ^2.2.0
  build_runner_core: ^7.2.3
  code_builder: ^4.2.0
  dart_style: ^2.2.3
  graphs: ^2.1.0
  io: ^1.0.3
  logging: ^1.0.2
  package_config: ^2.1.0
  path: ^1.8.1
  pub_semver: ^2.1.1
  source_gen: ^1.2.2
  yaml: ^3.1.1
#   path: ^1.8.0

dev_dependencies:
  build_test: ^2.1.5
  lints: ^2.0.0
  test: ^1.16.0
