name: beat_generator
description: A code genrator for beat state management. Heavily inspired by xstate.js.org
version: 0.6.1+2
repository: https://github.com/beatly-dev/beat
issue_tracker: https://github.com/beatly-dev/beat/issues

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.2.0
  beat: ^0.6.1+1
  build: ^2.3.0
  source_gen: ^1.2.2
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.11
  build_test: ^2.1.5
  lints: ^2.0.0
  test: ^1.16.0
