name: simple
description: A simple command-line application.
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  beat:
    path: ../../packages/beat_annotation
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  beat_generator:
    path: ../../packages/beat_generator
  build_runner:
  test:
