name: use_sender
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  beat:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  build_runner:
  beat_generator:
