name: beat_config
description: Configurations for the `beat_generator` package
version: 0.3.0
repository: https://github.com/beatly-dev/beat
issue_tracker: https://github.com/beatly-dev/beat/issues
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.16.0

dependencies: { json_annotation: ^4.6.0 }
