name: beat
description: A set of annotations for beat state management. Heavily inspired by xstate.js.org
version: 0.6.0
repository: https://github.com/beatly-dev/beat
issue_tracker: https://github.com/beatly-dev/beat/issues

environment:
  sdk: ">=2.17.5 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
